apiVersion: v1
kind: Pod
metadata:
  name: test-pd-env
spec:
  containers:
  - image: nginx
    name: test-container
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: nginx-credentials
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: nginx-credentials
            key: password
